// Generated by scripts/build-kaishi-levels.cjs — do not edit.
import type { ListeningTest } from './tests';
import level220 from './kaishi-1-220.json';
import level240 from './kaishi-1-240.json';
import level260 from './kaishi-1-260.json';
import level280 from './kaishi-1-280.json';
import level300 from './kaishi-1-300.json';
import level320 from './kaishi-1-320.json';
import level340 from './kaishi-1-340.json';
import level360 from './kaishi-1-360.json';
import level380 from './kaishi-1-380.json';
import level400 from './kaishi-1-400.json';
import level420 from './kaishi-1-420.json';
import level440 from './kaishi-1-440.json';
import level460 from './kaishi-1-460.json';
import level480 from './kaishi-1-480.json';
import level500 from './kaishi-1-500.json';
import level520 from './kaishi-1-520.json';
import level540 from './kaishi-1-540.json';
import level560 from './kaishi-1-560.json';
import level580 from './kaishi-1-580.json';
import level600 from './kaishi-1-600.json';

export const extraLevels = [level220, level240, level260, level280, level300, level320, level340, level360, level380, level400, level420, level440, level460, level480, level500, level520, level540, level560, level580, level600] as ListeningTest[];
